dist: trusty

branches:
  only:
  - master
  - dev


stages:
- name: build dev docker image
  if: branch = dev
- name: build prod docker image
  if: branch = master
  
jobs:
  include:
    - stage: build dev docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build --no-cache -t $DOCKER_USERNAME/listelab-web:dev ./ListElab/
      - docker images
      - docker tag $DOCKER_USERNAME/listelab-web:dev $DOCKER_USERNAME/listelab-web:dev
      - docker push $DOCKER_USERNAME/listelab-web:dev
    - stage: build prod docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build --no-cache -t $DOCKER_USERNAME/listelab-web ./ListElab/
      - docker images
      - docker tag $DOCKER_USERNAME/listelab-web $DOCKER_USERNAME/listelab-web
      - docker push $DOCKER_USERNAME/listelab-web

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
